[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "virex-bench"
dynamic = ["version", "urls"]
description = "ViREx-Bench: A framework for inference-time scaling on Vietnamese reasoning tasks."
readme = "README.md"
authors = [
  {name = "Minh-Thien Nguyen", email = "minhnguyent546@gmail.com"},
]
maintainers = [
  {name = "Minh-Thien Nguyen", email = "minhnguyent546@gmail.com"},
]
license = "GPL-3.0-only"
license-files = ["LICENSE"]
keywords = ["vietnamese", "reasoning", "benchmark", "logical-reasoning", "llm", "evaluation"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
requires-python = ">=3.12,<3.15"
dependencies = [
    "datasets>=5.0.0",
    "dspy>=3.2.1,<3.3.0",
    "loguru>=0.7.3",
    "pydantic>=2.10.0",
    "tqdm>=4.66.0",
    "torch==2.11.0",
    "torchvision==0.26.0",
    "transformers>=5.6.0,<5.12.0",
    "kernels>=0.14.1,<0.15.0",
    "z3-solver>=4.13.0,<4.15.5",
]

[project.scripts]
virex-bench = "virex_bench.cli:main"
vb = "virex_bench.cli:main"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.targets.wheel]
packages = ["virex_bench"]

[tool.hatch.metadata.hooks.vcs.urls]
Homepage = "https://github.com/minhnguyent546/ViREx-Bench"
Repository = "https://github.com/minhnguyent546/ViREx-Bench"
"Source commit" = "https://github.com/minhnguyent546/ViREx-Bench/commit/{commit_hash}"

[dependency-groups]
dev = [
    "colorama>=0.4.6",
    "coverage>=7.15.0",
    "hf-transfer>=0.1.9",
    "huggingface-hub>=0.36.0",
    "ipykernel>=7.1.0",
    "ipywidgets>=8.1.8",
    "jupyter>=1.1.1",
    "ninja>=1.13.0",
    "notebook>=7.5.5",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "pytest-cov>=7.1.0",
    "pytest-mock>=3.15.1",
    "ruff>=0.14.11",
    "tabulate>=0.9.0",
]
vllm-v0-20 = [
    "flashinfer-python>=0.6.8.post1; sys_platform == 'linux' and platform_machine == 'x86_64' and python_version == '3.12'",
    "vllm; sys_platform == 'linux' and platform_machine == 'x86_64' and python_version == '3.12'",
]
vllm-v0-23 = [
    "flashinfer-python>=0.6.11; sys_platform == 'linux' and platform_machine == 'x86_64' and python_version == '3.12'",
    "vllm==0.23.0; sys_platform == 'linux' and platform_machine == 'x86_64' and python_version == '3.12'",
    "transformers>=5.10.1; sys_platform == 'linux' and platform_machine == 'x86_64' and python_version == '3.12'",  # to support `gemma4_unified` arch
]
sglang-spec-v2-dflash-support = [
    "flashinfer-python>=0.6.8.post1; sys_platform == 'linux' and platform_machine == 'x86_64' and python_version == '3.12'",
    "sglang; sys_platform == 'linux' and platform_machine == 'x86_64' and python_version == '3.12'",
]
sglang-v0-5-14 = [
    "flashinfer-python>=0.6.12; sys_platform == 'linux' and platform_machine == 'x86_64' and python_version == '3.12'",
    "sglang; sys_platform == 'linux' and platform_machine == 'x86_64' and python_version == '3.12'",
    "transformers<5.9.0; sys_platform == 'linux' and platform_machine == 'x86_64' and python_version == '3.12'",
]

[tool.uv]
conflicts = [
  [
    { group = "vllm-v0-20" },
    { group = "vllm-v0-23" },
    { group = "sglang-spec-v2-dflash-support" },
    { group = "sglang-v0-5-14" },
  ]
]

[tool.ruff]
line-length = 99
target-version = "py312"
exclude = [
    "./thirdparty/",
]

[tool.ruff.lint]
select = [
    "B",      # flake8-bugbear
    "C",      # comple-structure
    "E",      # pycodestyle errors
    "F",      # pyflakes
    "I",      # isort
    "W",      # pycodestyle warnings
    "RUF013", # implicit-optional
    "UP006",  # non-pep585-annotation (e.g. `list[int]` instead of `List[int]`)
]
extend-safe-fixes = ["UP006"]
ignore = [
    "C901", # complex-structure
    "E101", # mixed-spaces-and-tabs
    "E501", # line-too-long
    "E741", # ambiguous-variable-name
    "F402", # import-shadowed-by-loop-var
    "F823", # undefined-local
]

[tool.ruff.lint.isort]
known-third-party = ["wandb"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = [
    "E402", # module-import-not-at-top-of-file
    "F401", # unused-import
    "F403", # undefined-local-with-import-star
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "session"
testpaths = ["tests"]
filterwarnings = [
  "ignore::DeprecationWarning:dspy.teleprompt.avatar_optimizer",
  "ignore::DeprecationWarning:dspy.predict.avatar.signatures",
]

[tool.coverage.run]
source = ["virex_bench"]
omit = ["tests/*"]

[tool.coverage.report]
show_missing = true
sort = "-Cover"
exclude_also = [
  "if TYPE_CHECKING:",
  "@abc.abstractmethod",
  "raise NotImplementedError",
  "logger.debug",
]

[tool.uv.sources]
vllm = [
    { group = "vllm-v0-20", url = "https://huggingface.co/datasets/minhnguyent546/wheelhouse/resolve/c9c295620142c173781e78a90ac2b7e25e9d7c7f/vLLM/vllm-0.20.2rc1.dev0+ge6ff3e9c8.d20260520-cp312-cp312-linux_x86_64.whl" },
]
sglang = [
    { group = "sglang-spec-v2-dflash-support", url = "https://huggingface.co/datasets/minhnguyent546/wheelhouse/resolve/490d7cea06b7f998eb36071ab2257cb0384249b6/SGLang/sglang-0.5.13.dev23+g93758bb00-cp312-cp312-linux_x86_64.whl"  },
    { group = "sglang-v0-5-14", url = "https://huggingface.co/datasets/minhnguyent546/wheelhouse/resolve/e8491995c210f7b3b1e4034d2d23bc957bdd136c/SGLang/sglang-0.5.14-cp312-cp312-linux_x86_64.whl"  },
]
